import '../styles/globals.css'
import Head from 'next/head';
import Navbar from "../layouts/Navbar"
import Footer from "../layouts/Footer"
import AOS from "aos";
import "aos/dist/aos.css";
import Loading from '../layouts/Loading';
import { useEffect } from 'react'
import WhatsApp from '../layouts/WhatsApp';

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    AOS.init({
      anchorPlacement: "top-left",
      duration: 600,
      easing: "ease-in-out",
      once: false,
      mirror: false,
      disable: false,
    });
  }, []);
  return (
    <>
      <Head>
        <title>hi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
          crossOrigin="anonymous"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossOrigin="anonymous"
        />
      </Head>
      <Navbar />
      <Loading />
      <Component {...pageProps} />
      <WhatsApp />
      <Footer />
    </>
  )
}

export default MyApp
