import Head from "next/head";
import Script from "next/script";
import Link from "next/link";
import styles from "../styles/Menu.module.css";
import axios from "axios";
import { useState, useEffect } from "react";
import Image from "next/image";
import Form from "../components/Form";
import Info from "../components/Info";

const contact = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="text-center pt-5">
        <div className="container py-5 mt-5">
          <div className="mb-5 pb-5 px-lg-5 px-1">
            <h2>Contact With us</h2>
            <p className="fw-bolder">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus minima corrupti possimus sint nemo molestias eligendi non dolorum rem consequuntur?</p>
          </div>
          <Form />
        </div>
      </main>
        <Info />
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossOrigin="anonymous"
      ></Script>
    </>
  )
}

export default contact