import Head from 'next/head'
import Script from 'next/script'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Section from '../components/Section'
import hImg from '../public/images/out.jpg'
import hImg2 from '../public/images/bookt.jpg'
import Swip from '../components/Swip'
import ScrollDownBtn from "../components/ScrollDownBtn"
import WhatsApp from '../layouts/WhatsApp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.headerHome}>
        <div className={styles.headerOverlay}></div>
        <div className="hello">
          <h1 data-aos="fade-up" data-aos-duration="300">Welcome to Belgravia Restaurant</h1>
          <p data-aos="fade-up" data-aos-duration="500">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos, est.</p>
          <Link href="/reservation">
            <a data-aos="fade-up" data-aos-duration="700" className="btn btn-lg shadow rounded-pill">Book a table</a>
          </Link>
          <ScrollDownBtn target="aboutSection" />
        </div>
      </header>
      <Section
        bg= "bg-light"
        revers= " "
        frameP= "left"
        HIM="HIM"
        aos="fade-right"
        img={hImg}
        imgalt = "belgravia"
        title= "About us"
        btn= "Read more"
        colimg= "col-md"
        coltext= "col-md"
        btnLink="/about"
        id="aboutSection"
      />
      <Section
        bg= " "
        revers= "flex-row-reverse"
        frameP= "right"
        HIM=" "
        aos="fade-left"
        img={hImg2}
        imgalt = "belgravia"
        title = "Reservation"
        btn= "Book a table"
        colimg= "col-md"
        coltext= "col-md"
        btnLink="/reservation"
      />
      <Swip />
      <WhatsApp />
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossOrigin="anonymous"></Script>
    </>
  )
}
