import Head from "next/head";
import Script from "next/script";
import Link from "next/link";

import ResForm from "../components/ResForm";

const reservation = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
          crossOrigin="anonymous"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossOrigin="anonymous"
        />
      </Head>
      <header className="bg-light reservation py-5">
        {/* <div className="header-overlay"></div> */}
        <div className="container mt-5">
          <div className="row align-items-center">
            <div className="col-md-6">
              <h2>book a table</h2>
              <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minima possimus excepturi quis pariatur ipsam vero, error consequatur itaque doloribus vel!</p>
            </div>
            <div className="col-md-6">
              <ResForm />
            </div>
          </div>
        </div>
      </header>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossOrigin="anonymous"
      ></Script>
    </>
  )
}

export default reservation