# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
        with:
          node-version: 16
 

      - name: Install python deps
        run: |
          pip install --upgrade pip
          python3 -m venv ./.venv
          ls -la ./.venv
          source ./.venv/bin/activate
          pip install -r deployment/requirements.txt

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 44.208.45.254

      - name: Build and compress files
        run: |
          npm install --location=global yarn
          yarn install
          yarn build
          tar -czf build.tar.gz ./.next
      


      - name: copy file via ssh key
        run: |
          ssh-keyscan -H 44.208.45.254 >> ~/.ssh/known_hosts
          scp -o StrictHostKeyChecking=no build.tar.gz ubuntu@44.208.45.254://home/ubuntu/blgrv/belgravia-next/

     
      - name: "Deploy project"
        run: |
          source ./.venv/bin/activate
          cd deployment
          fab update
